import { Inter } from 'next/font/google'
import './globals.css'
import Navber from '@/components/shared/Navber'
import Footer from '@/components/shared/Footer'
import { Container } from '@mui/material'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Navber></Navber>
        <Container className='min-h-screen'>
        {children}
        </Container>
      <Footer></Footer>
    </html>
  )
}
